steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/welspy-438208/welspy-fastapi-backend:0.3', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/welspy-438208/welspy-fastapi-backend:0.3']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances stop welpy-fastapi-backend --zone asia-northeast3-a   || true


        gcloud compute instances create-with-container welpy-fastapi-backend \
          --zone asia-northeast3-a \
          --container-image asia.gcr.io/welspy-438208/welspy-fastapi-backend:0.3 \

options:
  logging: CLOUD_LOGGING_ONLY
