services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: asia.gcr.io/welspy-438208/welspy-fastapi-backend:1.9
    platform: linux/x86_64
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
