services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: asia.gcr.io/welspy-438208/welspy-fastapi-backend:1.5
    platform: linux/x86_64
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - redis

  fastapi-backend-old:
    image: asia.gcr.io/welspy-438208/welspy-fastapi-backend:1.4
    platform: linux/x86_64
    ports:
      - "8001:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"