services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
